const data = {
  reviews: [
    {
      id: "63f3a4296f3134764b6f151d",
      filtered: false,
      pending: false,
      text: "We had never used Mobelaris before but will definitely be using them again. The company proved to friendly, efficient, professional and communicative. We ordered two Eames style DSW chairs in red to brighten up our dining room. They were very competitively priced and were delivered very promptly (despite a brief delay at a port). They were delivered in perfect condition and in good quality packaging. The chairs are perfect and the came with clear and simple instructions to fit the legs. \nMobelaris are a first rate firm to deal with and we’re pleased to be able to thoroughly recommend them.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-02-20T18:47:37.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "We had never used Mobelaris before but…",
      likes: 0,
      dates: {
        experiencedDate: "2023-02-20T00:00:00.000Z",
        publishedDate: "2023-02-20T18:47:37.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "606a14bb26bd26001b42a138",
        displayName: "Robert Harris",
        imageUrl: "",
        numberOfReviews: 3,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Robert,\n\nThank you for your 5 star review. It has always been our aim to bring you the same quality you would find from some of the top high street brands at a fraction of the price. No doubt you have fallen in love with DSW Style Chair, it will surely captivate your heart. The slender Four-legged Eiffel Tower wood base complements the seat.\n\nWe strive to always provide excellent customer service and a seamless shopping experience to all of our customers.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-02-21T13:17:08.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "6422f85bcb20decbb93eb1cc",
      filtered: false,
      pending: false,
      text: "I have bought many items from this company.  The customer service is excellent, with frequent updates on order progress etc.  The products are very good quality, and securely delivered, well packaged.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-28T16:23:23.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Excellent customer Service",
      likes: 0,
      dates: {
        experiencedDate: "2023-03-04T00:00:00.000Z",
        publishedDate: "2023-03-28T16:23:23.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5e8608a37ca6fb707b1c49c0",
        displayName: "Felicity Denby",
        imageUrl: "",
        numberOfReviews: 13,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Felicity,\n\nThank you for your awesome review. We're glad to hear that you are pleased with your purchases. We're glad you loved your Wishbone (Y) Chair - CH24 - Soaped Oak - Natural Cord and Cushion for Wishbone (Y) Chair CH24 - White Leather which is carefully handcrafted and we're sure you'll enjoy them for a long time!                                                         We always make sure that customers experience hassle free shopping and up to date with the progress of the order.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-03-29T09:47:21.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "642dd5b58f865660bb065875",
      filtered: false,
      pending: false,
      text: "Such a beautiful lamp to such a fair price. Absolutely love it! Would buy here again.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-04-05T22:10:29.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Such a beautiful lamp to such a fair…",
      likes: 0,
      dates: {
        experiencedDate: "2023-03-25T00:00:00.000Z",
        publishedDate: "2023-04-05T22:10:29.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5de5317c153b7e4a238f8d41",
        displayName: "Camilla Fronval",
        imageUrl: "",
        numberOfReviews: 29,
        countryCode: "DK",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Camilla,\n\nThank you for your glowing 5 star review, very much appreciated. We couldn't agree more as to how stunning the wishbone chairs are, handcrafted carefully and really well made. We strive to always provide excellent customer service and a seamless shopping experience to all of our customers.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris\n",
        publishedDate: "2023-04-06T14:27:14.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "64119d30191325fcb86610fa",
      filtered: false,
      pending: false,
      text: "Aubrey and the team at Mobelaris have been amazing! Ordering 8 chairs - when unfortunately only 3 were available, they managed to get the manufacturer to make 5 more to complete my order. The order was therefore in 2 batches some weeks apart - but the communication throughout was flawless. Aubrey would get in contact every couple of weeks (unprompted) to keep me updated on my order at the different stages which created a genuine sense of trust. I truly appreciate the extra mile… and now the chairs are here they look amazing!!! Exactly what I wanted!!!",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-15T12:25:52.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Aubrey and the team at Mobelaris have…",
      likes: 0,
      dates: {
        experiencedDate: "2023-03-15T00:00:00.000Z",
        publishedDate: "2023-03-15T12:25:52.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "64119cf0e1800800125145a7",
        displayName: "Jermain",
        imageUrl: "",
        numberOfReviews: 1,
        countryCode: "SE",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Jermain,\n\nThank you for your 5-star review. We're glad to hear that you're happy with your DSR Style Chair. It is a combination of elegance, light, and structural strength in one piece of furniture that can be mixed and matched with many different chairs, colors, and interiors. We strive to go above and beyond to provide a memorable and positive experience for our customers.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-03-15T14:06:56.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },

    {
      id: "6409869eee8ed659fa314b07",
      filtered: false,
      pending: false,
      text: "I ordered a wall light that has a long delivery time from other merchants. The goods were delivered perfectly packaged against possible damage. Very fast delivery.\nDaniel",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-09T09:11:26.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "I ordered a wall light that has a long…",
      likes: 0,
      dates: {
        experiencedDate: "2023-02-28T00:00:00.000Z",
        publishedDate: "2023-03-09T09:11:26.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "640986769f110c0016f6ce26",
        displayName: "Daniel",
        imageUrl: "",
        numberOfReviews: 1,
        countryCode: "CZ",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Daniel,\n\nThank you for your awesome feedback! We're glad to hear that you are pleased with your order Spider Wall Lamp 7 Arms - Black. We take great pride in our products, which are all made to a high standard of quality and manufactured to meet British safety requirements.\n\nIt was a pleasure doing business with you and we look forward to delivering to you again soon.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-03-09T14:38:20.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "640b025458c809f4ae34b68e",
      filtered: false,
      pending: false,
      text: "Mobelaris sell lighting not commonly available and their prices are a fraction of others. I was glad that the dispatch time was clear at point of sale. Delivery stress free. Im very happy with my purchases",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-10T12:11:32.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Mobelaris sell lighting not commonly…",
      likes: 0,
      dates: {
        experiencedDate: "2023-03-03T00:00:00.000Z",
        publishedDate: "2023-03-10T12:11:32.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "640b02319f110c0016f7bd5a",
        displayName: "Patsy",
        imageUrl: "",
        numberOfReviews: 1,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Patricia,\n\nThank you so much for your positive rating on our Melt Pendant Lamp. It has always been our goal to provide seamless shopping experience to our customers and provide superb customer service before, during and even after sales.\n\nLet us know if we can assist you with anything else in future.\n\nBest Wishes,\nMobelaris",
        publishedDate: "2023-03-10T16:16:35.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63f63c349b64b1bdaf5f77df",
      filtered: false,
      pending: false,
      text: "Excellent quality at a very reasonable price. I was pleasantly surprised about the good quality and the delivery was on time. They also helped me with some problem I had and their communication was very good and they also did their best to solve the problem in an accurate way. So I can recommend their service and will buy with them for sure.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-02-22T18:00:52.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Excellent quality at a very reasonable…",
      likes: 0,
      dates: {
        experiencedDate: "2023-01-19T23:00:00.000Z",
        publishedDate: "2023-02-22T18:00:52.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5474f3c8000064000199092c",
        displayName: "David Gent",
        imageUrl: "",
        numberOfReviews: 9,
        countryCode: "BE",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi David,\n\nThank you so much for your 5-star review. We're so happy to hear how much you love the quality of our Comfort Style 3-Seater Sofa - Alcantara - Charcoal Grey and Comfort Style Sofa Ottoman - Alcantara - Charcoal Grey. It has always been our aim to provide great quality products at an affordable price. \n\nIt was our pleasure assisting you we always make sure to provide good customer service before, during and even after sales\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-02-23T11:28:17.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63d6a8909b64b1bdaf4696fe",
      filtered: false,
      pending: false,
      text: "Nothing to complain about, got my 4 chair (looks great) after quite a long delay due to the shipping problems over the world. Customer support kept me updated on the order and responded on every question i had. I’m totally going to order again but maybe going for what’s in stock instead of waiting for manufacturing.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-01-29T19:10:40.000Z",
          reviewSourceName: "Organic",
          verificationSource: "invitation",
          verificationLevel: "not-verified",
          hasDachExclusion: false,
        },
      },
      title: "Just go for it.",
      likes: 0,
      dates: {
        experiencedDate: "2023-01-19T23:00:00.000Z",
        publishedDate: "2023-01-29T19:10:40.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5247e30a00006400014e49b3",
        displayName: "Johan",
        imageUrl: "",
        numberOfReviews: 5,
        countryCode: "SE",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Johan,\n\nThank you for your 5-Star review! We're really pleased to hear that you're happy with your Wishbone Chairs, they're one of our best sellers and we're sure you'll enjoy them for a long time. We always make sure that our customers are updated and in the loop at every stage on the progress of their orders.\n\nWe apologize for any delays encountered with your order and sincerely appreciate your patience and understanding. We look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-01-31T11:01:55.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "64098da9f19d4a8e965aaa50",
      filtered: false,
      pending: false,
      text: "I ordered a coffee table from mobelaris 21.02.23, and it was delivered at my door a little over a week later. I could track the shipment step by step, and they answered my emails quickly when I had questions. The quality of the coffee table is impeccable! Very pleased.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-09T09:41:29.000Z",
          reviewSourceName: "Organic",
          verificationSource: "invitation",
          verificationLevel: "not-verified",
          hasDachExclusion: false,
        },
      },
      title: "Excellent product!",
      likes: 0,
      dates: {
        experiencedDate: "2023-02-21T00:00:00.000Z",
        publishedDate: "2023-03-09T09:41:29.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "605e3c681f9c8e0019912bd9",
        displayName: "Anna Neraas",
        imageUrl: "",
        numberOfReviews: 3,
        countryCode: "NO",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Anna,\n\nThank you so much for your wonderful review. Noguchi Coffee Table is one of our best sellers and a perfect example of modernism. We're sure that you will enjoy it for a long time as it's very well made with careful attention to detail.\n\nIt was a pleasure doing business with you and we look forward to delivering to you again soon.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-03-09T14:48:50.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63d25b1b4b01fb3f548d6d74",
      filtered: false,
      pending: false,
      text: "Great product (Comfort Lounge Ottoman),\nReally well made, wonderfully packaged and delivered quickly!\nAlso, some of the best communication I have ever had from a furniture company. Reassuring, prompt and accurate every time. \nMy thanks to the entire Mobelaris team!\nHighly recommended.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-01-26T12:51:07.000Z",
          reviewSourceName: "Organic",
          verificationSource: "invitation",
          verificationLevel: "not-verified",
          hasDachExclusion: false,
        },
      },
      title: "Great product (Comfort Lounge Ottoman),",
      likes: 0,
      dates: {
        experiencedDate: "2023-01-26T00:00:00.000Z",
        publishedDate: "2023-01-26T12:51:07.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "60e64499d9ad6d0011bf0ced",
        displayName: "Chris",
        imageUrl: "",
        numberOfReviews: 6,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Chris,\n\nThank you for your awesome feedback!\n\nWe're happy to hear how much you love the quality of the Comfort Style Sofa Ottoman - Velvet - Bottle Green. This masterpiece is built for comfort. Nothing suggests relaxation and mellowed vibe more than this unique sofa. It will surely add a classy and exquisite feel to your home. It has always been our goal to provide seamless shopping experience to our customers and provide superb customer service before, during and even after sales.\n\nIt was a pleasure doing business with you and we look forward to delivering to you again soon.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-01-27T08:27:56.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63d5236a9b64b1bdaf45b116",
      filtered: false,
      pending: false,
      text: "From date of purchase kept me up to date on when I could expect delivery, I had ordered three of the same item and they all arrived, individually packed, together, this doesn't happen as often as it should. The products were extremely well packaged. The quality of the fabrication of the product was impressive, definitely in the style/build of the original.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-01-28T15:30:18.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Extremely pleased with this company.",
      likes: 0,
      dates: {
        experiencedDate: "2023-01-23T00:00:00.000Z",
        publishedDate: "2023-01-28T15:30:18.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "4e37480d00006400010a9dcc",
        displayName: "Mr. ANDREW MACLACHLAN",
        imageUrl: "",
        numberOfReviews: 7,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Andrew,\n\nWe are really pleased to receive your rating. Our PH 5 Pendant Lamp - Shades Of Red features a stunning design that combines industrial chic with a touch 20th century space-age retro style. It has always been our aim to bring you the same quality you would find from some of the top high street brands at a fraction of the price\n\nIt was a pleasure doing business with you and we look forward to delivering to you again soon.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-01-31T10:45:09.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "6422e46dbd8b325ce2587161",
      filtered: false,
      pending: false,
      text: "All according to description. Quick delivery and good prices!",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-28T14:58:21.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Tiptop",
      likes: 0,
      dates: {
        experiencedDate: "2023-03-15T00:00:00.000Z",
        publishedDate: "2023-03-28T14:58:21.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "6422e409481a950013bf2c36",
        displayName: "Adam Lindén",
        imageUrl:
          "https://user-images.trustpilot.com/6422e409481a950013bf2c36/73x73.png",
        numberOfReviews: 1,
        countryCode: "CH",
        hasImage: true,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Adam,\n\nThank you so much for your glowing review. We strive to always provide excellent customer service and a seamless shopping experience to all of our customers. We're glad to hear that you loved our Wishbone (Y) Chair - CH24 - Ash - Natural Cord which are carefully handcrafted and we're sure you'll enjoy them for a long time!\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-03-29T09:26:55.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63d77eae9b64b1bdaf46f7cd",
      filtered: false,
      pending: false,
      text: "Bought several items now as they are great, very well made products at very competitive prices. Very good customer relations and communication. \nI'll definitely be back to order more things in the future.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-01-30T10:24:14.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Bought several items now as they are…",
      likes: 0,
      dates: {
        experiencedDate: "2023-01-18T00:00:00.000Z",
        publishedDate: "2023-01-30T10:24:14.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5ad6ef804de5666d34765298",
        displayName: "Richard Jenkins",
        imageUrl: "",
        numberOfReviews: 4,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Richard,\n\nWe are really pleased to receive your rating and glad to hear that you are happy with your purchases and your new Panthella Style Floor Lamp. It has always been our aim to bring you the same quality you would find from some of the top high street brands at a fraction of the price. \n\nWe always make sure to provide superb customer service before, during, and even after sales and we’re happy to hear we hit the mark for you.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-01-31T11:20:47.000Z",
        updatedDate: "2023-01-31T11:22:06.000Z",
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63617fdbb84cc27618df7485",
      filtered: false,
      pending: false,
      text: "Many times, when you shop on-line the image and reality don't match. We ordered 10 chairs from Mobelaris and I was very pleased with the quality.  The chairs are well-made above expectations.  Furthermore, the delivery was easy to track and arrived on-time, in well-packed boxes with bubble wrap bags that we will definitely re-use...so bonus!  Overall, a fantastic on-line shopping experience!",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2022-11-01T22:21:48.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Fantastic on-line shopping experience!",
      likes: 0,
      dates: {
        experiencedDate: "2022-11-01T00:00:00.000Z",
        publishedDate: "2022-11-01T22:21:48.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "63617f643d398200130c2344",
        displayName: "Thomas Gleason",
        imageUrl: "",
        numberOfReviews: 1,
        countryCode: "SE",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Thomas,\n\nThank you for your awesome review! We Couldn't agree more! The CH23 chair is a lovely chair Its simplicity of design is enhanced by superb details of construction. We still have lots of items under our express delivery page that will help cut down the wait time.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2022-11-02T11:57:58.168Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63ee83309b64b1bdaf59ca02",
      filtered: false,
      pending: false,
      text: "Mobelaris had exactly what I wanted and at the right price. Shopping was prompt and communication throughout was perfect - I would definitely use them again.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-02-16T21:25:36.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Mobelaris had exactly what I wanted and…",
      likes: 0,
      dates: {
        experiencedDate: "2023-02-13T00:00:00.000Z",
        publishedDate: "2023-02-16T21:25:36.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "63ee832629a798001558c57b",
        displayName: "Patrick Douglas",
        imageUrl:
          "https://user-images.trustpilot.com/63ee832629a798001558c57b/73x73.png",
        numberOfReviews: 1,
        countryCode: "GB",
        hasImage: true,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Patrick,\n\nThank you for your awesome review. We're glad to hear that you're happy with your purchase with us. . We strive to always provide excellent customer service before, during, and even after-sales. No doubt you have fallen in love with DSW Style Chair, it will surely captivate your heart. The slender Four-legged Eiffel Tower wood base complements the seat.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-02-17T14:20:10.000Z",
        updatedDate: "2023-02-17T14:21:57.000Z",
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "6409ed8e61c84b47b036b44a",
      filtered: false,
      pending: false,
      text: "Loved the selection of well-priced items at Mobelaris -- and the speedy delivery of the Vertigo Style Ceiling Lamp I ordered!",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-03-09T16:30:38.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Loved the selection!",
      likes: 0,
      dates: {
        experiencedDate: "2023-02-17T00:00:00.000Z",
        publishedDate: "2023-03-09T16:30:38.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "56eda2f70000ff000a102359",
        displayName: "Dina",
        imageUrl: "",
        numberOfReviews: 16,
        countryCode: "GB",
        hasImage: false,
        isVerified: true,
      },
      reply: {
        message:
          "Hi Dina,\n\nThank you for your awesome feedback. We're glad you loved your Vertigo Ceiling Lamp.  has always been our aim to bring you the same quality you would find from some of the top high street brands at a fraction of the price.\n\nWe still have lots of items in stock or are coming in under our express delivery page for another seamless transaction.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-03-10T11:43:14.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "63caae6c4b01fb3f5487eeed",
      filtered: false,
      pending: false,
      text: "Have bought lights from Mobelaris a couple of times previously; although it's a long lead time, the quality has aways been very good and the pieces look great.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2023-01-20T17:08:28.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Good exerience with Mobelaris",
      likes: 0,
      dates: {
        experiencedDate: "2023-01-07T00:00:00.000Z",
        publishedDate: "2023-01-20T17:08:28.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "63caadcb90137b0011f248d2",
        displayName: "Max Elvin",
        imageUrl: "",
        numberOfReviews: 1,
        countryCode: "GB",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Max\nThank you so much for taking the time to leave us a 5 star rating - it's much appreciated! \n\nWe really appreciate you taking the time out to share your experience with us. We strive to always provide excellent customer service and a seamless shopping experience to all of our customers. We're glad you loved the quality of our Bubble Lamp Criss Cross Cigar - small. We count ourselves lucky for customers like you. \n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2023-01-21T16:36:55.000Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "638f92e50b7fc02715d648b7",
      filtered: false,
      pending: false,
      text: "Great choice and superb customer service.  Delighted with my Eames style office chair.  Have purchased from Mobelaris before and was also delighted with my two chairs which have pride of place in my sitting area.",
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2022-12-06T21:07:17.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Great choice and superb customer…",
      likes: 0,
      dates: {
        experiencedDate: "2022-12-05T00:00:00.000Z",
        publishedDate: "2022-12-06T21:07:17.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5b4536464de5666d3499e28b",
        displayName: "Siobhan Donnelly",
        imageUrl: "",
        numberOfReviews: 3,
        countryCode: "IE",
        hasImage: false,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Siobhan,\n\nThank you for your 5-Star feedback! We're so glad that you loved the quality of our Eames Style Office Chair EA108 Mesh. It has always been our aim to bring you the same quality you would find from some of the top high street brands at a fraction of the price. We always make sure to provide superb customer service before, during and even after sales and we’re happy to hear we hit the mark for you.\n\nIt was a pleasure doing business with you and we look forward to serving you again in the future.\n\nBest Wishes,\nTeam Mobelaris",
        publishedDate: "2022-12-08T11:47:59.000Z",
        updatedDate: "2022-12-12T08:02:18.000Z",
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
    {
      id: "62e1265a8000af4a884c5e78",
      filtered: false,
      pending: false,
      text: 'We have happily received our Togo replica ("Comfort Style Sofa and Ottoman") in Alcantara. Delivery and packaging was perfect …Naya from customer support helped us with any questions we had regarding shipping etc. (Thank you!). The quality/materials of the items is excellent, so we could not be happier with our purchase and how it was handled by Mobelaris...will buy from them again!',
      rating: 5,
      labels: {
        merged: null,
        verification: {
          isVerified: false,
          createdDateTime: "2022-07-27T13:49:46.000Z",
          reviewSourceName: "BasicLink",
          verificationSource: "invitation",
          verificationLevel: "invited",
          hasDachExclusion: false,
        },
      },
      title: "Togo replica (single and ottoman)",
      likes: 0,
      dates: {
        experiencedDate: null,
        publishedDate: "2022-07-27T13:49:46.000Z",
        updatedDate: null,
      },
      report: null,
      hasUnhandledReports: false,
      consumer: {
        id: "5ebe365d37a9ff1e2d6d7931",
        displayName: "Nope",
        imageUrl:
          "https://user-images.trustpilot.com/5ebe365d37a9ff1e2d6d7931/73x73.png",
        numberOfReviews: 3,
        countryCode: "GB",
        hasImage: true,
        isVerified: false,
      },
      reply: {
        message:
          "Hi Roman,\n\nThank you so much for the 5-star review. \n\nWe're happy to hear how much you love the quality of the Comfort Style Sofa Ottoman - Alcantara - Light Grey & Comfort Style Lounge Sofa - Alcantara - Light Grey. This masterpiece is built for comfort. Nothing suggests relaxation and mellowed vibe more than this unique sofa.\n\nIt was a pleasure doing business with you and we look forward to delivering to you again soon.\n\nBest Wishes,\nTeam Mobelaris\n",
        publishedDate: "2022-07-28T09:16:23.079Z",
        updatedDate: null,
      },
      consumersReviewCountOnSameDomain: 1,
      consumersReviewCountOnSameLocation: null,
      productReviews: [],
      language: "en",
      location: null,
    },
  ],
}
export default data
