const SUBSCRIBE_LIST = [
  {
    group_id: "W3aeZy",
    name: "Belgium (France) - Subscriber",
    slug: "belgium-france-subscriber",
    tags: null,
    countries: ["be"],
    group_type: 0,
    created: "2022-06-08T07:15:47+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "WuqnCM",
    name: "Subscriber - Italy",
    slug: "subscriber-italy",
    tags: null,
    countries: ["it"],
    group_type: 0,
    created: "2022-05-15T08:13:23+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },

  {
    group_id: "WH5LKF",
    name: "Austria - Subscribers",
    slug: "austria-subscribers",
    tags: null,
    group_type: 0,
    countries: ["at"],
    created: "2022-04-28T15:17:13+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "TQV6bv",
    name: "Germany - Subscriber",
    slug: "germany-subscriber",
    tags: null,
    countries: ["de"],
    group_type: 0,
    created: "2022-04-28T08:30:37+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "TT3Qvy",
    name: "France - Subscriber",
    slug: "france-subscriber",
    countries: ["fr"],
    tags: null,
    group_type: 0,
    created: "2022-04-28T07:14:03+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "TJ3TdX",
    name: "Netherlands - Subscriber",
    slug: "netherlands-subscriber",
    tags: null,
    group_type: 0,
    created: "2022-04-27T14:31:53+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "Wn3ACG",
    name: "Belgium (Dutch)- Subscriber",
    slug: "belgium-dutch-subscriber",
    tags: null,
    group_type: 0,
    created: "2022-04-27T12:58:02+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "WXxtJT",
    name: "EU - Subscribers",
    slug: "eu-subscribers",
    tags: null,
    countries: ["ie"],
    group_type: 0,
    created: "2022-04-26T14:18:38+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "WFRhwY",
    name: "Spain - Subscriber",
    slug: "spain-subscriber",
    tags: null,
    countries: ["es"],
    group_type: 0,
    created: "2022-04-25T12:41:59+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },

  {
    group_id: "TPezBr",
    name: "Norway - Subscriber",
    slug: "norway-subscriber",
    countries: ["no"],
    tags: null,
    group_type: 0,
    created: "2022-04-25T12:07:50+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "X2AP5y",
    name: "Sweden - Subscriber",
    slug: "sweden-subscriber",
    tags: null,
    countries: ["se"],
    group_type: 0,
    created: "2022-04-25T11:50:20+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
  {
    group_id: "Shptm2",
    name: "UK & Denmark Subsriber",
    slug: "uk-denmark-subsriber",
    tags: null,
    countries: ["gb"],
    group_type: 0,
    created: "2022-04-25T11:06:21+01:00",
    is_flagged: false,
    is_updating: false,
    update_percent_complete: 100,
    definition: null,
  },
]

export function getListId(countryCode: string) {
  let listId =
    SUBSCRIBE_LIST.find((item) => item.countries?.includes(countryCode))
      ?.group_id || "WXxtJT"
  return listId
}
